### ISSUE TITLE
Create Treasury Proposal form showing error for O account with > 100 LPT staked

### ISSUE THREAD

**Issue by dob** [livepeer/explorer#233] opened 2023-10-13 13:28 UTC
According to Chris Hobcroft in Discord

> Something isn't right with the "Create Proposal" form for the Treasury, at https://explorer.livepeer.org/treasury/create-proposal. I connected the wallet of an O with >100LPT staked to itself, but it gives me a message "Insufficient stake - you need at least 100.0 staked LPT to create a proposal." Is this a bug, or a misunderstanding?

**Comment by dob** [comment] 2023-10-13 15:08
Confirming I'm seeing this as well, and the Create proposal button is greyed out. 
![Screen Shot 2023-10-13 at 11 07 53 AM](https://github.com/livepeer/explorer/assets/10389/9ae9de63-674e-4a44-a4e6-f73b4d943447)

**Comment by victorges** [comment] 2023-10-13 15:40
crossposting

This is actually the expected behavior due to the way that the OZ Governor and our stake checkpoints work. It should be **fixed in 7 minutes** as the new round kicks in!

Details:
- The proposal threshold is enforced based on the _previous round_ stake, not the current round (or IOW, the current round _active stake_)
- This comes directly from the OZ Governor framework we built on top of, which we replicate the behavior in the explorer UI: https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.9.2/contracts/governance/GovernorUpgradeable.sol#L285
- Even though everyone does have active stake in their current round, no one had _checkpointed_ stake yet. So that `getVotes(proposer, currentTimepoint - 1)` on the previous timepoint above will give 0 stake for everyone rn
- Since all active Os have already called reward() in the current round, they are also checkpointed (happens automatically). Delegators that checkpointed themselves explicitly (there's a banner to incentivize that) will also be allowed in the next round

**Comment by victorges** [comment] 2023-10-17 16:57
closed per the above

**Closed by victorges** 2023-10-17 16:57 UTC
