### ISSUE TITLE
Incorrectly shows Rebond option after an account invokes transferBond() directly

### ISSUE THREAD

**Issue by yondonfu** [livepeer/explorer#58] opened 2022-03-23 21:05 UTC
There was a community report of the following:

- An account submitted a `transferBond()` tx to the BondingManager directly
- The UI shows a Rebond option
- Rebonding in this case is actually not possible since the unbonding lock created for the account in the `transferBond()` tx is immediately burned in the same tx after it is copied over to the receiver address

The Rebond option should not be shown in this case since rebonding wouldn't actually work.

**Comment by adamsoffer** [comment] 2022-05-09 03:18
Kautuk wasn't able to reproduce this issue and suspects the user may have encountered a delay in the UI after submitting the tx due to the explorer's reliance on the subgraph to check for unbonding locks (there's latency between when a tx confirms and when it gets indexed in the livepeer subgraph). Closing as that is a separate issue.

**Closed by adamsoffer** 2022-05-09 03:18 UTC
Labels: type: bug
